### ISSUE TITLE
Add background-agnostic theme

### ISSUE THREAD

**Issue by Jezorko** [ankurparihar/readme-pagespeed-insights#1]
The light / dark themes are awesome but I think a background-agnostic theme could be preferred by some.

I've modified the output SVG a bit to make that happen, here's how it looks like

![2020-08-10 17-40-57](https://user-images.githubusercontent.com/18513492/89802898-68b8a300-db32-11ea-8a57-1507753a1489.png)

Left column is current light theme output on both light and dark background. Right column is SVG with my improvements.

You can find the modified SVG and a simple page I used to display both images [here](https://github.com/ankurparihar/readme-pagespeed-insights/files/5051880/pagespeed-dark-theme-improvements.zip). Use `diff` to see the changes (:

**Comment by ankurparihar** [comment]
Thanks! This is awesome :)

Commit 01f2c9d96b289392d178e04cd86896a417d64010 closes this!
