### ISSUE TITLE
idea: caching results for some time

### ISSUE THREAD

**Issue by nin-jin** [ankurparihar/readme-pagespeed-insights#2]
Its allow to show an actual results on the page, instead of manual download and publish.

**Comment by ankurparihar** [comment]
Hi @nin-jin 

Real-time use of this is very costly. Currently there is PR https://github.com/ankurparihar/readme-pagespeed-insights/pull/3 
There is a GitHub action template which you can use to update the pagespeed svg after each commit and you will not have to manually download and publish each time!
