### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by sanidhyy** [ankurparihar/readme-pagespeed-insights#33]
![not working](https://user-images.githubusercontent.com/71302066/176728645-3c7c5960-cf81-44ea-93d5-7fb62493e7e4.png)

Some issue with heroku may be :(

**Comment by ankurparihar** [comment]
I get limited number of requests on Heroku, so around month end it gets exhausted and becomes unavailable.

Request you to  create one of your own heroku instance and deploy it there

**Comment by sanidhyy** [comment]
Ok bro 👍. You should add this info in **README** too.

**Comment by ankurparihar** [comment]
Sure, I actually had put this in to do list https://github.com/ankurparihar/readme-pagespeed-insights/issues/19 but couldn't get time to work on this.

I'll try to finish it this weekend now.

**Comment by sanidhyy** [comment]
Good Luck 👍
