### ISSUE TITLE
Heroku application throws application error

### ISSUE THREAD

**Issue by nico-i** [ankurparihar/readme-pagespeed-insights#34]
The [provided link](https://pagespeed-insights.herokuapp.com) for the application throws an error, which results in all other API requests also throwing an error.

**Comment by ankurparihar** [comment]
Hi 
please use a separate instance, I've got only limited quota.

**Comment by nico-i** [comment]
I tried out your suggestion by forking this repo and creating a new Heroku app with the fork, but now the app will not perform the speed test, no matter the URL I input as a query parameter. The following was the SVG I got when trying https://www.google.com/ as the param for the `url`.

![firefox_wMPEeM3TeL](https://user-images.githubusercontent.com/11136006/187636005-b8d0702a-00d2-4c0a-b829-3acf30070534.png)

This is what my console is outputting:

![firefox_eldvlI5d8F](https://user-images.githubusercontent.com/11136006/187636117-7cc9b594-2daf-4820-8728-ba9503443557.png)

**Comment by ankurparihar** [comment]
Hey

are you using Lastpass extension?

This onloadwff.js seems to be belonging to the extension which is crashing the page.
You may need to disable that extension

**Comment by nico-i** [comment]
@ankurparihar I deactivated the extension and the console error went away but the problem persisted. 😭

**Comment by ankurparihar** [comment]
okay @nico-i 
I'll try to look into this when I get some time

Additionally I'm planning some major revamp of this project, so hopefully it'll be fixed automatically

**Comment by nico-i** [comment]
Awsome! I was thinking about contributing myself for the upcoming Hacktoberfest, because I really like what you made here. You would have to add the #hacktoberfest tag to the issue though I think 🤗🎃
