### ISSUE TITLE
Not rendering the pagespeed insights and getting application error msg when using in readme file.

### ISSUE THREAD

**Issue by SarthakSKumar** [ankurparihar/readme-pagespeed-insights#35]
This is happening because the server is down, after heroku has stopped providing free dynos. A better approach would be to move the deployment from heroku to some other platform like vercel, cyclic etc.

**Comment by SarthakSKumar** [comment]
Issue is resolved now.

**Comment by ankurparihar** [comment]
I will try to find and implement using a better approach. Thank you for the support.
